### ISSUE TITLE
What is this plugin？

### ISSUE THREAD

**Issue by denstiny** [Th3Whit3Wolf/onebuddy#3]
![image](https://user-images.githubusercontent.com/57088952/105638218-6feb2780-5eac-11eb-911a-6e4349d60de9.png)

### You're a good match colors   I like it very much  At the same time I also like this

**Comment by Th3Whit3Wolf** [comment]
That is [minimap.vim](https://github.com/wfxr/minimap.vim)

**Comment by denstiny** [comment]
Thank you very much

**Comment by Th3Whit3Wolf** [comment]
No problem
