### ISSUE TITLE
There is something wrong with the floating window background color

### ISSUE THREAD

**Issue by denstiny** [Th3Whit3Wolf/onebuddy#4]
![image](https://user-images.githubusercontent.com/57088952/105640903-cf9cff00-5ebb-11eb-9024-139b068fb375.png)
### I'm sorry to disturb you again
I am a novice, but didn't find just checked a lot of related information
How do I modify the background color

**Comment by Th3Whit3Wolf** [comment]
What plugins is the popup coming from?

**Comment by denstiny** [comment]
coc-nvim

**Comment by Th3Whit3Wolf** [comment]
Try

```shell
:highlight floatHighlight guibg=None
```

**Comment by denstiny** [comment]
![image](https://user-images.githubusercontent.com/57088952/105720121-07f51980-5f5e-11eb-9015-e75071a444dd.png)
there is no effect

**Comment by Th3Whit3Wolf** [comment]
Try

```shell
:highlight CocFloating guibg=None
```

**Comment by denstiny** [comment]
![image](https://user-images.githubusercontent.com/57088952/105727295-e861ef00-5f65-11eb-95d7-33545fe5acf6.png)

 Still some problems

**Comment by denstiny** [comment]
Thank you, however, the problem is not big

**Comment by Th3Whit3Wolf** [comment]
What color are you wanting the background to be?

**Comment by denstiny** [comment]
![image](https://user-images.githubusercontent.com/57088952/105731700-a12a2d00-5f6a-11eb-9bac-d5048f9a5d2f.png)

# thank you ,i'm ok
