### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by Alan-SK** [Th3Whit3Wolf/onebuddy#5]
![ERROR](https://user-images.githubusercontent.com/69850287/106374775-ec0bd080-63c0-11eb-92b9-0ece362ebc3f.jpg)
What the hell is going on?

**Comment by hamsterBiscuit** [comment]
nvim version 0.5?

**Comment by Alan-SK** [comment]
No, It is 0.4.4

**Comment by hamsterBiscuit** [comment]
this plugin is run on >=0.5

**Comment by Th3Whit3Wolf** [comment]
Thank @hamsterBiscuit! @Alan-SK as @hamsterBiscuit onebuddy and all other plugins using [colorbuddy](https://github.com/tjdevries/colorbuddy.vim) require neovim version greater than 0.5. I see how that could be confusing as it's not mentioned in the README. I will update the README to reflect this requirement.
