### ISSUE TITLE
Disable Italics

### ISSUE THREAD

**Issue by Antonio-Bennett** [Th3Whit3Wolf/onebuddy#9]
Hey hope you are doing well :) Still a bit of a lua noob and neovim in general. Made the switch from vim and straight into lua from scratch. But my dumb terminal is bad with italics and they seem cut off which I think is a windows terminal thing since they don't support full italics or something. So yeah how do I disable italics? Or do I have to copy the setup and remove all the "i" in group?

**Comment by Th3Whit3Wolf** [comment]
Sorry to hear about that! You should be able to set `vim.g.onebuddy_disable_italics = true;` to disable italics now

**Comment by Antonio-Bennett** [comment]
Thanks a lot!!!

**Comment by Antonio-Bennett** [comment]
@Th3Whit3Wolf Hey sorry for bothering you but something weird is going on lol. So when I sent this I was still configuring and just got back into it and finished except comments are still italicized with disable italics set to true unless I manually set comments to no in the lua file. Here's a gif showing it (first line test comment ending T is cut off) so I have a fix just letting you know in case other people have the same issue :)

![Untitled_ Apr 12, 2021 4_53 PM](https://user-images.githubusercontent.com/31296212/114461700-0e378100-9bb0-11eb-8881-e8de00c66830.gif)

**Comment by Th3Whit3Wolf** [comment]
Thank you! When I get more free time I'll look more into the issue.

**Comment by Antonio-Bennett** [comment]
Okay great! Have a good week!
